name: sailorsport
on:
  pull_request:
    branches:
      - npm-sp
  pull_request_target:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: vercel-action
        with:
          github-token: ${{ secrets.GITH_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-comment: false
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_STATIC }}
      - name: preview-url
        run: |
          echo ${{ steps.vercel-action.outputs.preview-url }}